from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from datetime import datetime

def create_patent_pdf(sections, output_path="generated_patent.pdf"):
    doc = SimpleDocTemplate(output_path, pagesize=A4,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=72)

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='SectionTitle', fontSize=14, leading=16, spaceAfter=10, spaceBefore=20, bold=True))
    styles.add(ParagraphStyle(name='CustomBody', fontSize=11, leading=14))  # Renamed from BodyText

    story = []

    for title, content in sections.items():
        story.append(Paragraph(f"<b>{title}</b>", styles["SectionTitle"]))
        story.append(Paragraph(content if content else "N/A", styles["CustomBody"]))  # Use renamed style
        story.append(Spacer(1, 0.2 * inch))

    # Footer
    story.append(Spacer(1, 0.5 * inch))
    footer = Paragraph(
        f"<font size=8><i>Generated by PatentDoc Co-Pilot on {datetime.now().strftime('%Y-%m-%d %H:%M')}</i></font>",
        styles["Normal"]
    )
    story.append(footer)

    doc.build(story)
    return output_path
